openapi: "3.0.0"
info:
  title: "[Everest] - Node | Criação de Usuário"

  description: |-
    Essa api é basicamente responsável pela criação e inserção de um novo usuário dentro de um array mockado.
    Após ser feita a requição para o Backend, os dados do usuário são validados para verificar se não há nenhuma
    vulnerabilidade, caso haja, é retornado para o usuário um erro, caso contrário, o usuário é inserido no array.
  contact:
    email: diogenes.ribeiro@warren.com.br
  version: 1.0.0
externalDocs:
  description: SOLID API - Create User
  url: https://github.com/DiogenesRibeiroWarren/EV-TrilhaNode

servers: [{ url: http://localhost:8080/customer }]

tags:
  - name: Usuário
    description: Rota responsável por lidar e manipular os dados do usuário

paths:
  /customer:
    post:
      summary: Cadastro de usuário
      description: Essa rota será reponável por criar um novo usuário e inserir no Array Mockado
      tags:
        - Usuário

      requestBody:
        description: Corpo da requisição
        content:
          appllication/json:
            schema:
              $ref: "#/components/schemas/Usuario"
        required: true
      responses:
        "200":
          description: "[Usuário criado com sucesso] Quando o usuário preenche todos os dados corretamente"
          content:
            appllication/json:
              schema:
                $ref: "#/components/schemas/Usuario"
        "404":
          description: "[Preecha todos o campos corretamente] Quando o usuário deixa alguma campo em branco ou preenche com um dado incorreto"
        "500":
          description: "[Erro inesperado] Quando ocorre um erro inesperado no servidor"

components:
  schemas:
    Usuario:
      type: object
      properties:
        fullName:
          type: string
          example: Diógenes Ribeiro de Oliveira
        email:
          type: string
          example: diogenes.ribeiro@gmail.com
        emailConfirmation:
          type: string
          example: diogenes.ribeiro@gmail.com
        cpf:
          type: string
          example: "111.111.111-11"
        cellphone:
          type: string
          example: "51991020304"
        birthdate:
          type: string
          example: "10/01/2002"
        emailSms:
          type: boolean
          example: false
        whatsapp:
          type: boolean
          example: true
        country:
          type: string
          example: Brasil
        city:
          type: string
          example: Porto Alegre
        postalCode:
          type: string
          example: "182389-310"
        address:
          type: string
          example: Protásio Alves
        number:
          type: number
          example: 50
